<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Group_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get group by id_group
     */
    function get_group($id_group)
    {
        return $this->db->get_where('groups',array('id_group'=>$id_group))->row_array();
    }
        
    /*
     * Get all groups
     */
    function get_all_groups()
    {
        $this->db->order_by('id_group', 'desc');
        return $this->db->get('groups')->result_array();
    }
        
    /*
     * function to add new group
     */
    function add_group($params)
    {
        $this->db->insert('groups',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update group
     */
    function update_group($id_group,$params)
    {
        $this->db->where('id_group',$id_group);
        return $this->db->update('groups',$params);
    }
    
    /*
     * function to delete group
     */
    function delete_group($id_group)
    {
        return $this->db->delete('groups',array('id_group'=>$id_group));
    }
}
